#!/bin/bash
sudo yum update -y
sudo yum install -y docker
sudo curl -LOk https://github.com/zakkg3/docker-elk/archive/master.zip
sudo unzip master.zip
cd docker-elk-master/
sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo service docker start
sudo /usr/local/bin/docker-compose up
